### ISSUE TITLE
Value Error Problem

### ISSUE THREAD

**Issue by praksovar** [SJ001/AI-Feynman#4]
Hi Silviu,
Thank you very much for your useful code! Does ai_feynman requires the NVIDIA Graphic Card? Are there any other HW/SW requirements?
I am an author of Eureqa: software review you cited in your publication. I tried your code on my PC but at the end the ValueError of fname appeared (the same as KPL-T wrote in Issue#3). I tried to find the possible problem: In the script S_symmetry.py where command torch.cuda.is_available() returns 'False' for me. I don't have NVIDIA Graphic Card, so Cuda can't run on my PC. Could be this hardware the explanation of my problem? Is there any possibility to run you software without NVIDIA GPU?

Thank you in advance.
Renata

The error:
fh = iter(fname)
TypeError: 'int' object is not iterable
...............
During handling of the above exception, another exception occurred:
raise ValueError('fname must be a string, file handle, or generator')

ValueError: fname must be a string, file handle, or generator

**Comment by SJ001** [comment]
Hello Renata,

Thank you for the message and your interest in our code and I am sorry for the late reply. The code is mainly build to run using CUDA, but if that is not found, it should just run on the CPU (although probably much slower at the NN part). However, I found a bug that at a point it was forcing the code to run on CUDA and I fixed it. If the error you got was because of that the code should be working now. I don't think there are any requirements for the code, other than the ones in requirements.txt. Please let me know if you find other bugs or encounter any other issues (we are still adding features to the code, so things could easily break without us realizing immediately).
